# Generated by Django 5.0.8 on 2024-10-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tarım", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgricultureNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("published_at", models.DateTimeField()),
                ("url", models.URLField()),
            ],
        ),
    ]
