# Generated by Django 5.0.8 on 2024-10-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tarım", "0002_agriculturenews"),
    ]

    operations = [
        migrations.AddField(
            model_name="agriculturenews",
            name="image_url",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
